import { Poppins } from 'next/font/google'
import './globals.css'
import { ChakraProvider } from '@chakra-ui/react'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: 'GreenExchange',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  )
}
